### PR TITLE
PEP 572

### PR DESCRIPTION
**Pull request by vandys**
PEP 572 ":=" support, plus for orthogonality augmented assignments in general can be used
as expressions.  Passes all regression tests, documentation is updated as well.

### CODE REVIEW

**Comment by vandys** [comment]
I know, big change.  I'm just generating this push to make it easy for you to have a first look.

Regards... Andy

**Comment by stefantalpalaru** [comment]
Have you tried fixing this? https://travis-ci.org/naftaliharris/tauthon/jobs/406917028#L1177

**Comment by stefantalpalaru** [comment]
No, those tests are for your pull requests, and the problem appears only when configuring Tauthon with '--with-pydebug'. Do the same on your box to replicate the error.

**Comment by vandys** [comment]
Ok, will take a look, thanks.

**Comment by vandys** [comment]
Not sure why it's failing on zipfile; passing here on 32-bit and 64-bit?

**Comment by vandys** [comment]
Dunno, all tests run OK for me in 32- and 64-bit, with and without pydebug.  In the interests of
not putting a Heisenbug into the system, I'll withdraw the PR and dogfood it for a while.

**Comment by stefantalpalaru** [comment]
Could be MacOS specific: https://travis-ci.org/naftaliharris/tauthon/jobs/413727578#L2728

**Comment by vandys** [comment]
Good point, I'll dig up a Mac somewhere and try that.

**Pull request closed without merging**
