### PR TITLE
Implement PEP 3120 and update self-signed.pythontest.net.

### PR DESCRIPTION
**Pull request by luk3yx**
Implements [PEP 3120](https://www.python.org/dev/peps/pep-3120/), mostly copied from 447d33ead62b6dcd46d475a703f59940eb85428b.

~~This may introduce backwards incompatibilities if `eval("u'\xc2\xa3'")` is expected to return `u'\xc2\xa3'` and not `u'\xa3'`.~~

### CODE REVIEW

**Comment by graingert** [comment]
I don't think this is a good idea on tauthon, which is focussed on making not breaking changes from py2.7.16.

If someone wants to use utf8 source files they can use the encoding marker comment

**Comment by stefantalpalaru** [comment]
I don't think this would break existing Python2 code, but it needs to pass the CI tests.

**Comment by graingert** [comment]
Woops I was under the impression that py2 source was latin-1 by default.

> The default encoding was set to "ascii" in version 2.5.

**Comment by stefantalpalaru** [comment]
Thank you and sorry for the delay.

**Pull request merged**
